export const GET_LIST_USERS_REQUEST = 'GET_LIST_USERS_REQUEST';
export const GET_LIST_USERS_SUCCESS = 'GET_LIST_USERS_SUCCESS';
export const GET_LIST_USERS_FAILURE = 'GET_LIST_USERS_FAILURE';

export const IMPORT_REQUEST = 'IMPORT_REQUEST';
export const IMPORT_SUCCESS = 'IMPORT_SUCCESS';
export const IMPORT_FAILURE = 'IMPORT_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

export const GET_LIST_CHECKIN_CHECKOUT_REQUEST = 'GET_LIST_CHECKIN_CHECKOUT_REQUEST';
export const GET_LIST_CHECKIN_CHECKOUT_SUCCESS = 'GET_LIST_CHECKIN_CHECKOUT_SUCCESS';
export const GET_LIST_CHECKIN_CHECKOUT_FAILURE = 'GET_LIST_CHECKIN_CHECKOUT_FAILURE';

export const DOWNLOAD_REQUEST = 'DOWNLOAD_REQUEST';
export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS';
export const DOWNLOAD_FAILURE = 'DOWNLOAD_FAILURE';

export const GET_CHECK_LIST_REQUEST = 'GET_CHECK_LIST_REQUEST';
export const GET_CHECK_LIST_SUCCESS = 'GET_CHECK_LIST_SUCCESS';
export const GET_CHECK_LIST_FAILURE = 'GET_CHECK_LIST_FAILURE';

export const SUBMIT_CHECKLIST_ITEM_REQUEST = 'SUBMIT_CHECKLIST_ITEM_REQUEST';
export const SUBMIT_CHECKLIST_ITEM_SUCCESS = 'SUBMIT_CHECKLIST_ITEM_SUCCESS';
export const SUBMIT_CHECKLIST_ITEM_FAILURE = 'SUBMIT_CHECKLIST_ITEM_FAILURE';
